//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class իմ_սարքած_սյունը
    {
        public short FrndId { get; set; }
        public string FstName { get; set; }
        public string LstName { get; set; }
        public Nullable<System.DateTime> BthDate { get; set; }
        public string Ntel { get; set; }
    }
}
